openapi: 3.1.0
info:
  title: ''
  description: ''
  version: 0.0.0
servers:
  -
    url: /
    description: ''
paths:
  /api/example_api_resources:
    get:
      operationId: api_example_api_resources_get
      tags:
        - ExampleApiResource
      responses:
        '200':
          description: 'ExampleApiResource resource'
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/ExampleApiResource.jsonld.output'
            application/json:
              schema:
                $ref: '#/components/schemas/ExampleApiResource'
        '404':
          description: 'Resource not found'
      summary: 'Retrieves a ExampleApiResource resource.'
      description: 'Retrieves a ExampleApiResource resource.'
      parameters: []
      deprecated: false
components:
  schemas:
    ExampleApiResource:
      type: object
      description: ''
      deprecated: false
    ExampleApiResource.jsonld.output:
      type: object
      description: ''
      deprecated: false
      properties:
        '@context':
          oneOf:
            -
              type: string
            -
              type: object
              properties:
                '@vocab':
                  type: string
                hydra:
                  type: string
                  enum: ['http://www.w3.org/ns/hydra/core#']
              required:
                - '@vocab'
                - hydra
              additionalProperties: true
        '@id':
          type: string
        '@type':
          type: string
      required:
        - '@context'
        - '@id'
        - '@type'
  responses: {  }
  parameters: {  }
  examples: {  }
  requestBodies: {  }
  headers: {  }
  securitySchemes: {  }
security: []
tags: []
webhooks: {  }
