openapi: 3.1.0
info:
  title: ''
  description: ''
  version: 0.0.0
servers:
  -
    url: 'https://0.0.0.0'
    description: ''
paths:
  /api/example_api_resources:
    post:
      operationId: api_example_api_resources_post
      tags:
        - ExampleApiResource
      responses:
        201:
          description: 'ExampleApiResource resource created'
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/ExampleApiResource.jsonld'
            application/json:
              schema:
                $ref: '#/components/schemas/ExampleApiResource'
          links: {  }
        400:
          description: 'Invalid input'
        422:
          description: 'Unprocessable entity'
      summary: 'Creates a ExampleApiResource resource.'
      description: 'Creates a ExampleApiResource resource.'
      parameters: []
      requestBody:
        description: 'The new ExampleApiResource resource'
        content:
          application/ld+json:
            schema:
              $ref: '#/components/schemas/ExampleApiResource.jsonld'
          application/json:
            schema:
              $ref: '#/components/schemas/ExampleApiResource'
        required: true
      deprecated: false
    parameters: []
components:
  schemas:
    ExampleApiResource:
      type: object
      description: ''
      deprecated: false
    ExampleApiResource.jsonld:
      type: object
      description: ''
      deprecated: false
      properties:
        '@context':
          readOnly: true
          oneOf:
            -
              type: string
            -
              type: object
              properties:
                '@vocab':
                  type: string
                hydra:
                  type: string
                  enum: ['http://www.w3.org/ns/hydra/core#']
              required:
                - '@vocab'
                - hydra
              additionalProperties: true
        '@id':
          readOnly: true
          type: string
        '@type':
          readOnly: true
          type: string
  responses: {  }
  parameters: {  }
  examples: {  }
  requestBodies: {  }
  headers: {  }
  securitySchemes: {  }
security: []
tags: []
