openapi: 3.1.0
info:
  title: ''
  description: ''
  version: 0.0.0
servers:
  -
    url: /
    description: ''
paths:
  /api/health-check:
    get:
      operationId: health_check
      tags:
        - HealthCheckDto
      responses:
        '200':
          description: 'HealthCheckDto resource'
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/HealthCheckDto.jsonld-output'
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckDto-output'
        '404':
          description: 'Resource not found'
      summary: 'Retrieves a HealthCheckDto resource.'
      description: 'Retrieves a HealthCheckDto resource.'
      parameters: []
      deprecated: false
components:
  schemas:
    HealthCheckDto-output:
      type: object
      description: ''
      deprecated: false
    HealthCheckDto.jsonld-output:
      type: object
      description: ''
      deprecated: false
      properties:
        '@context':
          readOnly: true
          oneOf:
            -
              type: string
            -
              type: object
              properties:
                '@vocab':
                  type: string
                hydra:
                  type: string
                  enum: ['http://www.w3.org/ns/hydra/core#']
              required:
                - '@vocab'
                - hydra
              additionalProperties: true
        '@id':
          readOnly: true
          type: string
        '@type':
          readOnly: true
          type: string
  responses: {  }
  parameters: {  }
  examples: {  }
  requestBodies: {  }
  headers: {  }
  securitySchemes: {  }
security: []
tags: []
webhooks: {  }
