services:
    _defaults:
        autowire: true
        autoconfigure: true

    Symfony\Contracts\Cache\CacheInterface:
        public: true
        class: Symfony\Component\Cache\Adapter\FilesystemAdapter

    App\Tests\Behat\:
        resource: '../tests/Behat/*'
