resources:
  App\Internal\HealthCheck\Domain\ValueObject\HealthCheck:
    operations:
      ApiPlatform\Metadata\Get:
        path: '/health'
        processor: 'App\Internal\HealthCheck\Application\Processor\HealthCheckProcessor'
