name: bats core tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  my_test:
    runs-on: ubuntu-latest
    name: Install Bats and bats libs
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ vars.PHP_VERSION }}

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Start Application
        run: make start

      - name: Setup Bats and bats libs
        uses: bats-core/bats-action@2.0.0
        with:
          support-path: '/tests/CLI/bats'
          assert-path: '/tests/CLI/bats'

      - name: Run Bats tests
        run: make bats
