name: Code Lint and Prettify

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-prettify:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}  # default; safe to omit

      - name: Detect GPG key availability
        id: gpg-check
        run: |
          if [ -n "${{ secrets.GPG_PRIVATE_KEY }}" ]; then
            echo "HAS_GPG_KEY=true" >> "$GITHUB_ENV"
          fi

      - name: Import GPG key
        if: ${{ github.event_name == 'push' && env.HAS_GPG_KEY == 'true' }}
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite
          coverage: none

      - name: Cache Composer packages
        uses: actions/cache@v4
        with:
          path: |
              ~/.composer/cache/files
              vendor
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-${{ runner.os }}-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Run PHP CS Fixer
        run: CI=1 make phpcsfixer

      - name: Run Rector
        run: CI=1 make rector-apply

      - name: Commit changes
        if: github.event_name == 'push' && github.actor != 'github-actions[bot]'
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git add -u
            git commit -m "style: auto-fix code style and apply rector transformations"
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "No changes to commit"
          fi
