name: test coverage

on:
  pull_request:
    branches: [ "main" ]

jobs:
  codecov:
    runs-on: ubuntu-latest
    name: run codecov
    steps:
      - uses: actions/checkout@master
      - uses: docker-practice/actions-setup-docker@master
      - name: Make start
        run: make start
      - name: Run tests and collect coverage-xml
        run: make coverage-xml
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true