name: E2E testing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  behat:
    name: Behat
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ vars.PHP_VERSION }}

      - name: Start Application
        run: make start

      - name: Composer update
        run: make update

      - name: Install Dependencies
        run: make install

      - name: Setup Test Database
        run: make setup-test-db

      - name: Run Behat Tests
        run: make e2e-tests
