name: E2E testing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  behat:
    name: Behat
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Permissions
        run: sudo chmod -R 777 .

      - name: Start Application
        run: make start

      - name: Setup Test Database
        run: make setup-test-db

      - name: Run Behat Tests
        run: make e2e-tests
