name: GraphQL spec backward compatibility

on:
  pull_request:
    branches: [ "main" ]

jobs:
  graphql-diff:
    name: Openapi-diff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ vars.PHP_VERSION }}

      - name: Install Dependencies with Retry
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Start Application
        run: make start

      - name: Generate GraphQL Spec
        run: make generate-graphql-spec

      - name: Copy GraphQL Spec to Host
        run: docker cp php-service-template-php-1:/srv/app/.github/graphql-spec/spec .github/graphql-spec/spec

      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          add: '.github/graphql-spec/spec'
          message: 'feat(#${{ toJSON(github.event.number) }}): generate graphql spec'

      - name: GraphQL Inspector
        uses: kamilkisiela/graphql-inspector@release-1701263349990
        with:
          schema: 'master:.github/graphql-spec/spec'
