name: Load testing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  load-tests:
    name: K6
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run tests
        run: make aws-load-tests
        continue-on-error: false
