name: openapi-diff

on:
  pull_request:
    branches: [ "main" ]

jobs:
  openapi-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Check out head branch
        uses: actions/checkout@v2
        with:
          path: head
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate openapi spec
        run: php bin/console api:openapi:export --yaml --output=.github/openapi-spec/spec.yaml
      - name: Check out master branch
        uses: actions/checkout@v2
        with:
          ref: master
          path: base
      - name: Run OpenAPI Diff (from HEAD revision)
        uses: mvegter/openapi-diff-action@v0.23.5
        with:
          head-spec: head/.github/openapi-spec/spec.yaml
          base-spec: base/.github/openapi-spec/spec.yaml