name: Generate badges
on:
  push:

jobs:
  badges:
    name: Generating badges
    runs-on: ubuntu-latest
    steps:
      - name: Generate PhpInsights badges
        uses: Lukasss93/phpinsights-badger@v1
        with:
          url: 'https://yourservice.com' # Required: your lumen service url
          password: ${{ secrets.password }} # Required: your lumen service password
          path : './test.json' # Required: the test.json generated file path from phpinsights
